### ISSUE TITLE
Site is not mobile friendly 

### ISSUE THREAD

**Issue by mrsrabs** [W-OVERFLOW/W-OVERFLOW.github.io#2]
**Operating system** - Android 9 

**Browser** - Chrome

**Issue**: The website is not mobile friendly; the side panel is not visible in mobile and the right side of the page is blank white so kinda like the half site is visible.

**Screenshots**: 
![Screenshot_2021-12-28-11-40-22-30](https://user-images.githubusercontent.com/71704374/147532291-ffdb2ef2-6a08-4e01-8b3c-f2bb362ba896.jpg)
![Screenshot_2021-12-28-11-39-53-49](https://user-images.githubusercontent.com/71704374/147532318-6babeff6-155c-4632-b1c0-bcee80f71c30.jpg)

**Comment by pauliesnug** [comment]
#3 :D
